Bbox to detected_person conveter
sbgisen/spencer_people_tracking pull request #4
Opened 2023-10-16 02:14 UTC by Tacha-S

## Summary

bounding box + class から detected personsに変換するノードの追加

- fix #

## Detail

## Impact

## Test

  

## Attention

2023-10-17 05:57 UTC, jsupratman13 requested changes

2023-10-17 05:57 UTC, jsupratman13 commented on detection/spencer_detected_person_conversion/scripts/bbox_to_detected_persons.py
> +            self.__detection_id += self.__detection_id_increment
detection_idを上げ続けていいの？

2023-10-17 17:07 UTC, Tacha-S commented on detection/spencer_detected_person_conversion/scripts/bbox_to_detected_persons.py
> +            self.__detection_id += self.__detection_id_increment
他のconverterに合わせてます

2023-10-18 01:40 UTC, jsupratman13 commented on detection/spencer_detected_person_conversion/scripts/bbox_to_detected_persons.py
> +            self.__detection_id += self.__detection_id_increment
ok

2023-10-18 01:40 UTC, jsupratman13 approved these changes, later dismissed

2023-10-18 01:52 UTC, jsupratman13 requested changes
jsk_recognition_msgs依存関係はいらないの？

2023-11-01 01:27 UTC, jsupratman13 approved these changes

2023-11-01 01:27 UTC, merged